travis:
  secure:
    BINSTAR_TOKEN: FcHQLb5zV0dfRGw3zYEuBIf00lf9Vm2HYojGWdE4mM9RAUnAJzSiic0Sz3rKPLyPBesATWFSR9Nebi4ND05W3moq4DQlSl3dQOJ3Hc5vMsSyI2kdGC55Y+aOuVcWT+/W6hxSC7QeEQQEykqf5i2tmszY53YwUU3pYUC6+ysk68zuhdUUCvgaMRxUi1XMk4teuKL4MLAVd6TOaIRgPsHZxNjUnYp8qup6UjhgX91FJNyw4lZbLr0KdkTYYwJcYTlp8soQ7tykcwYzT6IhNRa5mLeL4sMuToGOYUAFqS1E0PDhjqnix1z14XRvELFordjyDhUqy9dilYZIvNaVgGT5b1IQvBozWM3fZ9rWJnZRDiU5tgd5rZ9LTq1LOv4FFXCxQhjsTZn7yjjTGWxptd66arWVeD4/TCGxb7/N/yPQTUhcPpcZfHaEt2b/Xzil+F3gWEm1r0pNZg0k1Na9ez6VgNvd5xZ7AtUeywUvNf3S6Bj4kkcD50O5sntTK3Q+XFGIYuK0knM6yzDLb8oUYktT4I3eEdvXsMQDBp1JMg+JfSqGE9Y+DjFQpsWwtrlmyd+Sg6QN6bd47tQN4iy1fr5eEvX+0mgveepDegkcuZGESp6W5q1eCn7vhGJpyw2AHu2DCBBQxuSA91ljpkKOoUwjUpDBHy4YPOQYF5Cx9vFWw0o=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
