travis:
  secure:
    BINSTAR_TOKEN: fVxfsVvm0wLKfqRn6K45y/XG7LHQgFs/ZLyKEC0VafNuQqjgzIawR6TRFfS6PuccNAVTfDwYr0ltuN8JSSHTXtqjCuqeav0kMHDScSeFpcDc3Ua8ccSEUCUfoe/igSOftbu5AIhw+v9/6A/qAY14oKdOyQc1j66eYnVzuU0GcclY0Tauo+oa9OKtDzr77alr7FicX8IpHsdkou7G4xbxOFllRfgs5TI1Fjg7g6Kta7x95YkRQFYgyhc3I7pdg1MObQXQdjeAWlnfTaVdnOooKMhc61ODb7n6cEfWLpp7heG5I2oAMjQpUObU2t2sVh18HqQw2NYkEsaS0nvKaulbdmNI+HR/1ofbbN93bOT+/koAfLWsiZ+putZ6/Hg6Q+f14myTM/De2V2eKtVihTHbT9SlemCUZ51HxkNv16aMVrBVPBf+9lCz/wW19buXc3n7IBHurEwp3bcHtq0lVZz2V/ivr+YTn2v4Vcj1kqLDnyCTNrOMmrUMevCINedlCVacznKUU9Wt+FCkETlELshC6v5Csj8apwBubQN9zJLXoNMYCn/at00sv4quENzcXxDkxNdAUELJqPB81v5wUWQ92klVGPzVH45+L9nw0SIqvLszQ/kPa56WqhHwSHQAUj/NDrx7uF2qUrW3Ec6gxdt+3EIAlUQytbstwowIpiysdPc=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
